# Generated by Django 5.2 on 2025-05-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_todo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Date',
            field=models.DateField(),
        ),
    ]
